[build]
  base    = ""  # Base directory for the build process, leave it blank to use the root directory
  publish = "public"  # Directory to publish the built files
  command = "npm install && npm run build"  # Command to run for building your project

[functions]
  directory = "netlify/functions"  # Directory for Netlify functions (serverless functions)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
